pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: .+
    docker:
      credentials:
        description: quay.io robot
      uri: quay.io
    slack:
      channel: 'git-notifications'
  branches:
    master:
      steps:
        - docker:
          - build:
              imageName: reynn/jenkins
              imageTag: "2.107"
              buildArgs:
                JENKINS_VERSION: "2.107-alpine"
              dockerfile: jenkins.dockerfile
          - build:
              imageName: reynn/helm-client
              imageTag: v2.7.2
              buildArgs:
                HELM_VERSION: "v2.7.2"
                KUBECTL_VERSION: "v1.9.0"
              dockerfile: helm.dockerfile
          - push:
              imageName: reynn/jenkins
              imageTag: "2.107"
          - push:
              imageName: reynn/helm-client
              imageTag: v2.7.2
