pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: .+
    docker:
      credentials:
        description: quay.io robot
      uri: quay.io
    jenkins:
      workflows:
        branch: docker-changes
    slack:
      channel: 'git-notifications'
  branches:
    master:
      steps:
        - docker:
          - build:
              imageName: reynn/jenkins
              imageTag: "2.107"
              buildArgs:
                JENKINS_VERSION: "2.107-alpine"
              dockerfile: jenkins.dockerfile
          - build:
              imageName: reynn/helm-client
              imageTag: v2.7.2
              buildArgs:
                HELM_VERSION: "v2.7.2"
                KUBECTL_VERSION: "v1.9.0"
              dockerfile: helm.dockerfile
          - build:
              imageName: reynn/python3-base
              dockerfile: python3-base.dockerfile
          - build:
              imageName: reynn/python2-base
              dockerfile: python2-base.dockerfile
          - build:
              imageName: reynn/packer-alpine
              imageTag: "1.2.0"
              buildArgs:
                PACKER_VERSION: "1.2.0"
              dockerfile: packer.dockerfile
          - push:
              imageName: reynn/jenkins
              imageTag: "2.107"
              additionalTags:
                - latest
          - push:
              imageName: reynn/helm-client
              imageTag: v2.7.2
              additionalTags:
                - latest
          - push:
              imageName: reynn/python2-base
              additionalTags:
                - latest
          - push:
              imageName: reynn/python3-base
              additionalTags:
                - latest
          - push:
              imageName: reynn/packer-alpine
              imageTag: "1.2.0"
              additionalTags:
                - latest
